"
" vimrc
"

set clipboard+=unnamed

set helplang=ja,en
set number
set cursorline
set laststatus=2
set whichwrap=b,s,h,l,<,>,[,],~
set mouse=a
inoremap jj <Esc>
syntax on
set backspace=indent,eol,start

set cindent
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4

set ignorecase
set smartcase
set incsearch
set wrapscan
set hlsearch

set list
set listchars=tab:>_,eol:$

" netrw
let g:netrw_altv=1
let g:netrw_alto=1
let g:netrw_winsize=85
let g:netrw_keepdir=0

" file
set noswapfile

" quickfix
autocmd QuickFixCmdPost *grep* cwindow
autocmd QuickFixCmdPost *make* cwindow

"
" end
"

